# Generated by Django 3.1.2 on 2020-10-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=32)),
                ('customer_fullname', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('inspection', 'Inspection'), ('basic tuneup', 'Basic Tuneup'), ('advanced tuneup', 'Adanced Tuneup'), ('flat-fix', 'Flat-Fix'), ('bike assembly', 'Bike Assembly'), ('bike packing', 'Bike Packing')], max_length=15)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='profiles.userprofile')),
            ],
        ),
    ]
