# Generated by Django 3.1.2 on 2020-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20201027_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('inspection', 'Inspection'), ('basic tuneup', 'Basic Tuneup'), ('advanced tuneup', 'Advanced Tuneup'), ('flat-fix', 'Flat Fix'), ('bike assembly', 'Bike Assembly'), ('bike packing', 'Bike Packing')], max_length=15),
        ),
    ]
