# Generated by Django 3.1.2 on 2020-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201029_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='recommend',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
