# Generated by Django 3.1.2 on 2020-11-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201031_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_desc',
        ),
    ]
